export const BirdActionTypes = {
    RESIZE_SCREEN: 'RESIZE_SCREEN',
    CHECK_FOR_OVERLAPS : 'CHECK_FOR_OVERLAPS',
    CHANGE_EYE_COLOR : 'CHANGE_EYE_COLOR',
    TRIGGER_GROWING : 'SET_GROWING',
    GROW_HEAD : 'GROW_HEAD',
    FIX_BIRD : 'FIX_BIRD',
    ADD_BASE_BIRD : 'ADD_BASE_BIRD',
    ADD_BIRD : 'ADD_BIRD',
    CHECK_NEIGHBORS : 'CHECK_NEIGHBORS',
    INCREMENT_IDX : 'INCREMENT_IDX',
    REMOVE_BIRD : 'REMOVE_BIRD',
    TICKER_STARTED : 'TICKER_STARTED',
    TICKER_STOPPED : 'TICKER_STOPPED',
    TICK_TIME : 'TICK_TIME',
    UPDATE_CLICKED : 'UPDATE_CLICKED',
    BREATHE_ALL : 'BREATHE_ALL'

}